;;KEYBINDINGS
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "C-!") 'set-frame-name)
(global-set-key (kbd "M-<left>") 'previous-buffer)
(global-set-key (kbd "M-<right>") 'next-buffer)
(global-set-key (kbd "M-<up>") 'windmove-right)
(global-set-key (kbd "M-<down>") 'windmove-left)
(global-set-key [f2] 'helm-gtags-find-symbol)
(global-set-key (kbd "C-<f2>") 'helm-gtags-find-pattern)
(global-set-key [f3] 'rtags-find-symbol-at-point)
(global-set-key [f4] 'helm-gtags-dwim)
(global-set-key (kbd "C-<f4>") 'helm-gtags-find-files)
(global-set-key (kbd "C-<f3>") 'helm-gtags-find-rtag)
(global-set-key [f8] 'semantic-ia-complete-symbol-menu)
(global-set-key (kbd "C-<f6>") 'cscope-find-this-symbol)
(global-set-key (kbd "C-x C-b") 'ibuffer)
(global-set-key (kbd "C-c C-c") 'c-mode)
(global-set-key (kbd "C-<f7>") 'cscope-find-functions-calling-this-function)
(global-set-key (kbd "M-g") 'goto-line)
(global-set-key [f12] 'helm-gtags-create-tags)
(global-set-key [f11] 'set-local-database)
(global-set-key [f10] 'set-block-database)
(global-set-key [f5] 'term-line-mode)
(global-set-key [f6] 'term-char-mode)
(global-set-key (kbd "<f7>") (lambda ()
                               (interactive)
                               (setq-local compilation-read-command nil)
                               (call-interactively 'compile)))

(global-set-key (kbd "C-/") 'comment-or-uncomment-region)
(global-set-key (kbd "C-å") 'bookmark-set)
(global-set-key (kbd "C-ä") 'bookmark-jump)
(global-set-key (kbd "C-<tab>") 'projectile-find-other-file)
(global-set-key (kbd "C-r") 'revert-buffer)
;;(global-set-key (kbd "§") 'complete)
